import numpy as np
ones_array=np.ones((2,3))
zeros_array=np.zeros((2,3))
empty_array=np.empty((2,3))
print("ones:\n",ones_array)
print("zeros:\n,zeros_array")
print("empty=\n",empty_array)
arr=np.array([1,2,3],[3,6])
print("shaped of array:",arr.shape)
reshaped=arr.reshaped(3,2)
print("reshaped array:\n,reshaped")
arr1=np.array([1,2,3])
copy_arr1=arr.copy()
view_arr1=arr.view()
print("original:",arr1)
print("copy:",copy_arr1)
print("view:",view_arr1)
arr2=np.array([1,2])
arr3=np.array[(3,4)]
concatenated=np.concatenated((arr2,arr3))
print("concatenated array:",concatenated)
array=np.array([5,2,9,1])
print("sorted array:",np.sort(arr))