a = str(input("Enter a string: "))
uppercase = a.upper()
print(f"Uppercase: {uppercase}")
lowercase = a.lower()
print(f"Lowercase: {lowercase}")
title_case = a.title()
print(f"Title case: {title_case}")
length = len(a)
print(f"Length: {length}")
